# Generated by Django 3.2.4 on 2022-01-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20220111_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postcategory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.postcategory', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lng',
            field=models.FloatField(default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='definition',
            field=models.CharField(max_length=510, verbose_name='Описание питомца'),
        ),
    ]
