# Generated by Django 3.2.4 on 2022-01-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220111_0409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='definition',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=1, max_length=125, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
