# Generated by Django 3.2.4 on 2022-01-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_phone_post_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='title',
            field=models.CharField(max_length=70, verbose_name='Название категории'),
        ),
    ]
