# Generated by Django 3.2.4 on 2022-01-10 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_postcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typeanimal', verbose_name='Вид питомца'),
        ),
    ]
